movieproject/movieapp/urls.py
from django.urls import path
from . import views
from .views import update

app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.addmovie,name='addmovie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls")),

]
if settings.DEBUG:
     urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
     urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=300)
    description=models.TextField()
    year=models.IntegerField()
    ticketrate=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','description','year','ticketrate','img']

movieproject/movieapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={'movie_list':movie}
    return render(request,'index.html',context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})

def addmovie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        description=request.POST.get('description',)
        year=request.POST.get('year',)
        ticketrate=request.POST.get('ticketrate',)
        img=request.FILES['img']
        movie=Movie(name=name,description=description,year=year,ticketrate=ticketrate,img=img)
        movie.save()
    return render(request,"addmovie.html")

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/addmovie.html
{% extends 'base.html' %}
{% block body %}
<body style="color:#d4ac0d ">
<center>
    <form method="POST" enctype="multipart/form-data" style="color:black ">
{%csrf_token%}
    <input type="text" name="name" placeholder="Enter movie name"><br>
    <input type="text" name="description" placeholder="What your movie tells about"><br>
    <input type="text" name="year" placeholder="Which year your movie got released?"><br>
    <input type="text" name="ticketrate" placeholder="Enter movie ticketrate"><br>
    <input type="file" name="img" placeholder="Enter an image represents your movie"><br>
    <input type="submit">

</form>
</center>
</body>
{% endblock %}

movieproject/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}" >
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
       The Movie Store
      <li> <a href="{% url 'movieapp:addmovie'%}" class="btn btn-primary" style="background-color:#d68910;border:#d68910;align:right; ">Add another movie</a></li>

<!--    <img src="/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">-->

  </a>
</nav>
{% block body %}
{% endblock %}
</body>


</html>

movieproject/templates/delete.html
{% extends 'base.html' %}

{% block body %}
<center>
<form method="post">
    {% csrf_token %}
    You want to delete this movie?<br>
    <input type="submit">
</form>
</center>
{% endblock %}

movieproject/templates/detail.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img src="{{ movie.img.url }}" width="350" height="300" align="left">
        </div>
        <div class="col-md-3" align="justify">
            <h5><strong>{{movie.name}}</strong></h5>
            <h6>{{movie.year}}</h6>
            <h6>{{movie.description}}</h6>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}" style="color:white;">Want to update?</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}" style="color:white;">Want to delete?</a>

        </div>
    </div>
</div>
{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}

{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit</title>
</head>
<body>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
</body>
</html>
{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-sm-4">
            <div class="card" style="width: 18rem; background-color: #f5b041
">
  <img src="{{i.img.url}}" class="card-img-top" alt="..." width="200px" height="150px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.year}} </p>
    <a href="{% url 'movieapp:detail' i.id%}" class="btn btn-primary" style="background-color:#d68910;border:#d68910">View Details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}